### ISSUE TITLE
frida.core.RPCException: Error: access violation accessing 0x7ff61e206000

### ISSUE THREAD

**Issue by addressnopping** [ergrelet/unlicense#108]
Hello, I was trying to unpack a program and it happened. Here is the full log: 

INFO - Detected packer version: 3.x
frida-agent: Setting up OEP tracing for "nescher_2.exe"
frida-agent: Exception handler registered
frida-agent: OEP found (thread #6032): 0x7ff61e1c2744
INFO - OEP reached: OEP=0x7ff61e1c2744 BASE=0x7ff61e0d0000 DOTNET=False
INFO - Looking for the IAT...
INFO - Performing linear scan in data sections...
Traceback (most recent call last):
  File "unlicense\frida_exec.py", line 116, in read_process_memory
  File "frida\core.py", line 179, in method
  File "frida\core.py", line 86, in wrapper
  File "frida\core.py", line 491, in _rpc_request
frida.core.RPCException: Error: access violation accessing 0x7ff61e206000
    at readProcessMemory (/script1.js:386)
    at apply (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:13)
    at c (frida/runtime/message-dispatcher.js:23)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "unlicense\__main__.py", line 4, in <module>
  File "unlicense\application.py", line 21, in main
  File "fire\core.py", line 141, in Fire
  File "fire\core.py", line 466, in _Fire
  File "fire\core.py", line 681, in _CallAndUpdateTrace
  File "unlicense\application.py", line 122, in run_unlicense
  File "unlicense\winlicense3.py", line 24, in fix_and_dump_pe
  File "unlicense\winlicense3.py", line 59, in _find_iat
  File "unlicense\winlicense3.py", line 84, in _find_iat_from_data_sections
  File "unlicense\frida_exec.py", line 124, in read_process_memory
unlicense.process_control.ReadProcessMemoryError
[15008] Failed to execute script '__main__' due to unhandled exception!

**Comment by clowncs** [comment]
Hi, im currently facing with this issue too. Do you have any fix after this ?
