### ISSUE TITLE
Detected packer version: 3.x

### ISSUE THREAD

**Issue by SaSukiTB** [ergrelet/unlicense#25]
Any idea how to fix this

> Traceback (most recent call last):
  File "unlicense\__main__.py", line 4, in <module>
  File "unlicense\application.py", line 20, in main
  File "fire\core.py", line 141, in Fire
  File "fire\core.py", line 466, in _Fire
  File "fire\core.py", line 681, in _CallAndUpdateTrace
  File "unlicense\application.py", line 73, in run_unlicense
  File "unlicense\frida_exec.py", line 152, in spawn_and_instrument
  File "frida\__init__.py", line 57, in spawn
  File "frida\core.py", line 26, in wrapper
  File "frida\core.py", line 149, in spawn
frida.NotSupportedError: unable to spawn executable at 'Loader.exe': 0x000002e4
[3760] Failed to execute script '__main__' due to unhandled exception!

**Comment by ergrelet** [comment]
Hi! This basically means calling `CreateProcess` failed. In this case, `0x000002e4` corresponds to `ERROR_ELEVATION_REQUIRED`.
It means that the target executable requires to be run as an administrator but `unlicense` isn't being run as an administrator.
