### ISSUE TITLE
frida.NotSupportedError

### ISSUE THREAD

**Issue by AbrilDEVlua** [ergrelet/unlicense#39]
INFO - Detected packer version: 3.x

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Abril\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\unlicense.exe\__main__.py", line 7, in <module>
  File "C:\Users\Abril\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\unlicense\application.py", line 20, in main
    fire.Fire(run_unlicense)
  File "C:\Users\Abril\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\Abril\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\Abril\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\Abril\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\unlicense\application.py", line 78, in run_unlicense
    process_controller = frida_exec.spawn_and_instrument(
  File "C:\Users\Abril\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\unlicense\frida_exec.py", line 162, in spawn_and_instrument
    pid = frida.spawn((str(pe_path), ))
  File "C:\Users\Abril\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\frida\__init__.py", line 59, in spawn
    return get_local_device().spawn(*args, **kwargs)
  File "C:\Users\Abril\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\frida\core.py", line 34, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Abril\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\frida\core.py", line 157, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)

frida.NotSupportedError: unable to spawn executable at 'C:\Users\Abril\Desktop\mogker\unlicense\Updater.exe': 0x000002e4

**Comment by maximumfrogs** [comment]
Hello, did you ever find a solution to this problem?
