### ISSUE TITLE
Error: access violation accessing 0xe05000

### ISSUE THREAD

**Issue by AhmedZero** [ergrelet/unlicense#5]
Good job for that tool.
anyway, there is an exception when resolving imports.

OS: Windows 11

the stack exception
```
frida-agent: Setting up OEP tracing for "unpackchallenge.exe"
frida-agent: Possible OEP (thread #19448): 0x640029
INFO:unlicense:OEP reached: OEP=0x640029 BASE=0x5c0000)
INFO:unlicense.winlicense3:IAT found: 0xe05000
INFO:unlicense.winlicense3:Resolving imports ...
Traceback (most recent call last):
  File "M:\My_Projects\unlicense\unlicense\frida_exec.py", line 91, in write_process_memory
    self._frida_rpc.write_process_memory(address, data)
  File "C:\Users\Abo Tabekh\AppData\Roaming\Python\Python39\site-packages\frida\core.py", line 468, in method
    return script._rpc_request('call', js_name, args, **kwargs)
  File "C:\Users\Abo Tabekh\AppData\Roaming\Python\Python39\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Abo Tabekh\AppData\Roaming\Python\Python39\site-packages\frida\core.py", line 400, in _rpc_request
    raise result[2]
frida.core.RPCException: Error: access violation accessing 0xe05000
    at writeProcessMemory (/script1.js:129)
    at apply (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:13)
    at c (frida/runtime/message-dispatcher.js:23)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_86\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_86\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "M:\My_Projects\unlicense\unlicense\__main__.py", line 4, in <module>
    main()
  File "M:\My_Projects\unlicense\unlicense\application.py", line 19, in main
    fire.Fire(run_unlicense)
  File "C:\Users\Abo Tabekh\AppData\Roaming\Python\Python39\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\Abo Tabekh\AppData\Roaming\Python\Python39\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\Abo Tabekh\AppData\Roaming\Python\Python39\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "M:\My_Projects\unlicense\unlicense\application.py", line 84, in run_unlicense
    winlicense3.fix_and_dump_pe(process_controller, exe_to_dump,
  File "M:\My_Projects\unlicense\unlicense\winlicense3.py", line 25, in fix_and_dump_pe
    unwrap_res = _unwrap_iat(iat_range, process_controller)
  File "M:\My_Projects\unlicense\unlicense\winlicense3.py", line 118, in _unwrap_iat
    process_controller.write_process_memory(
  File "M:\My_Projects\unlicense\unlicense\frida_exec.py", line 93, in write_process_memory
    raise WriteProcessMemoryError from e
unlicense.process_control.WriteProcessMemoryError

```

**Comment by ergrelet** [comment]
Hi! Thanks for your interest in the project.

That's interesting, it fails to overwrite the IAT. I've never had this happen with the samples I have. Would you mind sharing your sample so I can reproduce the issue?

**Comment by AhmedZero** [comment]
how can I share?
send me your email to contact you.

**Comment by ergrelet** [comment]
> how can I share? send me your email to contact you.

You can send your sample to this e-mail: unlicense@laposte.net

**Comment by ergrelet** [comment]
@AhmedZero This issue should be fixed with the latest commit.
I noticed there might be an issue with OEP recovery though, but I'll take care of that in another issue.
