### ISSUE TITLE
ERROR - ERROR: invalid parameters

### ISSUE THREAD

**Issue by x1362** [ergrelet/unlicense#55]
Log：

INFO - Detected packer version: 3.x
frida-agent: Setting up OEP tracing for "b.exe"
frida-agent: Exception handler registered
frida-agent: TLS callback #0 detected (at 0x401a60), skipping ...
frida-agent: TLS callback #1 detected (at 0x401a10), skipping ...
frida-agent: OEP found (thread #16064): 0x4014e0
INFO - OEP reached: OEP=0x4014e0 BASE=0x400000 DOTNET=False
INFO - IAT found: 0x40614c
INFO - Resolving imports ...
ERROR - ERROR: invalid parameters
INFO - Imports resolved: 60
INFO - Fixed IAT at 0x40614c, size=0xeb8
INFO - Dumping PE with OEP=0x4014e0 ...
INFO - Fixing dump ...
Traceback (most recent call last):
  File "unlicense\__main__.py", line 4, in <module>
  File "unlicense\application.py", line 20, in main
  File "fire\core.py", line 141, in Fire
  File "fire\core.py", line 466, in _Fire
  File "fire\core.py", line 681, in _CallAndUpdateTrace
  File "unlicense\application.py", line 105, in run_unlicense
  File "unlicense\winlicense3.py", line 36, in fix_and_dump_pe
  File "unlicense\dump_utils.py", line 78, in dump_pe
  File "unlicense\dump_utils.py", line 104, in _rebuild_pe
  File "unlicense\dump_utils.py", line 130, in _resolve_section_names
lief.not_found: No section associated with the data directory 'RESOURCE_TABLE'
[89212] Failed to execute script '__main__' due to unhandled exception!

How to solve it?
[b.zip](https://github.com/ergrelet/unlicense/files/9721901/b.zip)

**Comment by ergrelet** [comment]
Hi!
Commit https://github.com/ergrelet/unlicense/commit/01c02ae5d4e7d4edcc54a7f5542f27de97e6a1fa on the `dev` branch should fix this, you can try it out.

**Comment by ergrelet** [comment]
Fix is now on `main`, I'm closing this issue.

**Comment by xiu-shen** [comment]
Hello, I am facing the same problem as you. I follow the author's advice to use the latest code, but I have encountered new problems，dll Make a mistake,Missing entry:#0”.
Do you have the same problem?
