### ISSUE TITLE
lief.not_found: No section associated with the data directory 'RESOURCE_TABLE'

### ISSUE THREAD

**Issue by sami-soft** [ergrelet/unlicense#58]
INFO - Detected packer version: 2.x
frida-agent: Setting up OEP tracing for "1.exe"
frida-agent: Exception handler registered
frida-agent: OEP found (thread #5896): 0xd21f72
INFO - OEP reached: OEP=0xd21f72 BASE=0xc90000 DOTNET=False
INFO - Looking for wrapped imports ...
INFO - Potential import wrappers found: 478
INFO - Generating exports' hashes, this might take some time ...
INFO - Resolving imports ...
**ERROR - ERROR:** 
INFO - Imports resolved: 184
INFO - Generated the fake IAT at 0x920000, size=0x2e0
INFO - Patching call and jmp sites ...
INFO - Dumping PE with OEP=0xd21f72 ...
INFO - Fixing dump ...
Traceback (most recent call last):
  File "C:\Users\samisoft\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\samisoft\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\samisoft\AppData\Local\Programs\Python\Python310-32\Scripts\unlicense.exe\__main__.py", line 7, in <module>
  File "C:\Users\samisoft\AppData\Local\Programs\Python\Python310-32\lib\site-packages\unlicense\application.py", line 20, in main
    fire.Fire(run_unlicense)
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\samisoft\AppData\Local\Programs\Python\Python310-32\lib\site-packages\fire\core.py", line 466, in _Fire  
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\samisoft\AppData\Local\Programs\Python\Python310-32\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\samisoft\AppData\Local\Programs\Python\Python310-32\lib\site-packages\unlicense\application.py", line 102, in run_unlicense
    winlicense2.fix_and_dump_pe(process_controller, pe_to_dump,
  File "C:\Users\samisoft\AppData\Local\Programs\Python\Python310-32\lib\site-packages\unlicense\winlicense2.py", line 111, in fix_and_dump_pe
    dump_pe(process_controller, pe_file_path, image_base, oep, iat_addr,
  File "C:\Users\samisoft\AppData\Local\Programs\Python\Python310-32\lib\site-packages\unlicense\dump_utils.py", line 78, 
in dump_pe
    _rebuild_pe(output_file_name)
  File "C:\Users\samisoft\AppData\Local\Programs\Python\Python310-32\lib\site-packages\unlicense\dump_utils.py", line 104, in _rebuild_pe
    _resolve_section_names(binary)
  File "C:\Users\samisoft\AppData\Local\Programs\Python\Python310-32\lib\site-packages\unlicense\dump_utils.py", line 130, in _resolve_section_names
    hex(data_dir.section.virtual_address))
**lief.not_found**: No section associated with the data directory 'RESOURCE_TABLE'

**Comment by ergrelet** [comment]
Hi! This issue has been fixed on the `main` branch.

You can use the latest version by doing `pip install git+https://github.com/ergrelet/unlicense.git`, or wait for the next release (which has no ETA).

**Comment by sami-soft** [comment]
> Hi! This issue has been fixed on the `main` branch.
> 
> You can use the latest version by doing `pip install git+https://github.com/ergrelet/unlicense.git`, or wait for the next release (which has no ETA).

Yes, I tested this main branch. but there is a problem
