### ISSUE TITLE
frida.NotSupportedError

### ISSUE THREAD

**Issue by D34DlyM4N** [ergrelet/unlicense#68]
unlicense1.exe test.exe --verbose --force_oep --target_version=3

it's not working

INFO - Detected packer version: 3.x
DEBUG - Probed .text section at (0x1000, 0xb31e0)
Traceback (most recent call last):
  File "unlicense\__main__.py", line 4, in <module>
  File "unlicense\application.py", line 20, in main
  File "fire\core.py", line 141, in Fire
  File "fire\core.py", line 466, in _Fire
  File "fire\core.py", line 681, in _CallAndUpdateTrace
  File "unlicense\application.py", line 78, in run_unlicense
  File "unlicense\frida_exec.py", line 162, in spawn_and_instrument
  File "frida\__init__.py", line 57, in spawn
  File "frida\core.py", line 26, in wrapper
  File "frida\core.py", line 149, in spawn
frida.NotSupportedError: unable to spawn executable at 'test.exe': 0x000002e4
[18340] Failed to execute script '__main__' due to unhandled exception!

**Comment by SahilSingh021** [comment]
Yea, I am also curious as to why this is happening... Would love to know if you have found any workarounds.

**Comment by alexrp** [comment]
That's `ERROR_ELEVATION_REQUIRED`. Try running Unlicense with elevation? (Obviously with the caveat that doing so outside a VM is a Very Bad Idea if you don't trust the program you're trying to unpack.)
