### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_section'

### ISSUE THREAD

**Issue by ghost** [ergrelet/unlicense#71]
Traceback (most recent call last):
  File "unlicense\__main__.py", line 4, in <module>
  File "unlicense\application.py", line 20, in main
  File "fire\core.py", line 141, in Fire
  File "fire\core.py", line 466, in _Fire
  File "fire\core.py", line 681, in _CallAndUpdateTrace
  File "unlicense\application.py", line 43, in run_unlicense
  File "unlicense\version_detection.py", line 14, in detect_winlicense_version
AttributeError: 'NoneType' object has no attribute 'get_section'
[28996] Failed to execute script '__main__' due to unhandled exception!

**Comment by xiu-shen** [comment]
> 
hello i have the analogus problem, Have you solved this problem now？

**Comment by ergrelet** [comment]
Hi, the latest version from `main` has better logging in these cases now. It's probably that you're not trying to unpack a valid executable (i.e., PE) file.
