### ISSUE TITLE
frida.InvalidOperationError: script has been destroyed

### ISSUE THREAD

**Issue by nbuhell** [ergrelet/unlicense#75]
unlicense CrySystem.dll --target_version=2

INFO - Detected packer version: 2.x
frida-agent: Setting up OEP tracing for "CrySystem.dll"
frida-agent: Target module has been loaded (thread #23140) ...
frida-agent: Exception handler registered
frida-agent: OEP found (thread #23140): 0x10163e31
INFO - OEP reached: OEP=0x10163e31 BASE=0x10000000 DOTNET=False
Traceback (most recent call last):
  File "D:\PythonX86\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\PythonX86\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\PythonX86\Scripts\unlicense.exe\__main__.py", line 7, in <module>
  File "D:\PythonX86\lib\site-packages\unlicense\application.py", line 20, in main
    fire.Fire(run_unlicense)
  File "D:\PythonX86\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\PythonX86\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "D:\PythonX86\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "D:\PythonX86\lib\site-packages\unlicense\application.py", line 102, in run_unlicense
    winlicense2.fix_and_dump_pe(process_controller, pe_to_dump,
  File "D:\PythonX86\lib\site-packages\unlicense\winlicense2.py", line 47, in fix_and_dump_pe
    for mem_range in process_controller.main_module_ranges:
  File "D:\PythonX86\lib\site-packages\unlicense\process_control.py", line 104, in main_module_ranges
    self._main_module_ranges = self.enumerate_module_ranges(
  File "D:\PythonX86\lib\site-packages\unlicense\frida_exec.py", line 75, in enumerate_module_ranges
    value: List[Dict[str, Any]] = self._frida_rpc.enumerate_module_ranges(
  File "D:\PythonX86\lib\site-packages\frida\core.py", line 476, in method
    return script._rpc_request('call', js_name, args, **kwargs)
  File "D:\PythonX86\lib\site-packages\frida\core.py", line 34, in wrapper
    return f(*args, **kwargs)
  File "D:\PythonX86\lib\site-packages\frida\core.py", line 408, in _rpc_request
    raise result[2]
frida.InvalidOperationError: script has been destroyed

[CrySystem.zip](https://github.com/ergrelet/unlicense/files/10895594/CrySystem.zip)

**Comment by ergrelet** [comment]
Hi! I pushed a fix on the `dev` branch that fixes the issue 👍
