### ISSUE TITLE
frida.NotSupportedError: unable to spawn executable at

### ISSUE THREAD

**Issue by ivkraft** [ergrelet/unlicense#93]
unlicense .\BwE_PS4_NOR_Validator.exe                     in pwsh at 07:45:49
INFO - Detected packer version: 3.x
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\Scripts\unlicense.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\unlicense\application.py", line 21, in main
    fire.Fire(run_unlicense)
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\unlicense\application.py", line 84, in run_unlicense
    process_controller = frida_exec.spawn_and_instrument(
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\unlicense\frida_exec.py", line 165, in spawn_and_instrument
    pid = frida.spawn(str(pe_path))
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\frida\__init__.py", line 66, in spawn
    return get_local_device().spawn(program=program, argv=argv, envp=envp, env=env, cwd=cwd, stdio=stdio, **kwargs)
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\frida\core.py", line 968, in spawn
    return self._impl.spawn(program, **kwargs)
frida.NotSupportedError: unable to spawn executable at 'BwE_PS4_NOR_Validator.exe': 0x00000020

**Comment by ergrelet** [comment]
Hi! This error code means "The process cannot access the file because it is being used by another process." so you probably have another process interfering with the dumping on your machine.
